# Generated by Django 2.0.3 on 2018-04-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
    ]
