# Generated by Django 2.0.3 on 2018-04-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0002_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.TextField(default='Unknown Type'),
        ),
    ]
